language: python
python:
 - "3.6.6"
install:
 - pip install -r requirements.txt
sudo: required
services:
 - docker
notifications:
  email: false
before_install:
 - cd docker
 - docker-compose up -d
 - cd ..
jobs:
  include:
    - stage: tests
      script:
        - cd docker
        - docker exec -ti decide_web ./manage.py test
        - cd ..
      if: branch = ortosia-postproc AND type = pull_request
    - stage: "Postproc tests"
      script:
        - cd docker
        - docker exec -ti decide_web ./manage.py test postproc
        - cd ..
      if: branch =~ ^ortosia-postproc-.{9}$
    - stage: deploy
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          ortosia-postproc:
            secure: Pc+jLY1rIuKcyzOAB4s8vwtrJx7vl3p/5/ha8Rmq7nbwBLB9gwePpVcgjEAh+mFWeL1EJ2w8XfporEPpEG6W5f/da4ku2HXufHuI2Nj7Qeap462Iggt/9VN7dfElVCOv5tN7mPM6bQTQmnrFwTU319zOXE8qEyMehISBl5bgDqmf9MG+H3m2899wdUuvy2Jf78BRGjld4rMzYzoOI0zYBdA0IT2OTlEdIEapAh0B51LttQa2skAmlSPXmUPJ6pK8zoczwd7KrnnUqni7JJm/6k6JA4ysgDKjG7mT2fmmo1QNn+jMn3SSPjfwTuntw7K6sxXAK1ILjkb3v2dz9KJxPvUVmS087QLlZzjJfx/qsLfHSZBZ5ZmcEg0Q9LwEJMp2u+Xq+O0/RKKeXuM7pEJxw0nZNjZkpVhL/W5UNalVbMsiqZDP0j/6Q9EL+wIfqaN/KRQYuJAfO0NbGVuvW39RR3Frcal1yyEXg2f/8Pl5XqTt+5r3JoVeNN+6GSbeXyln90u16NZT/+f12ruS6xMeIXzCQIQevCA0RokoBTPCd9ftgTHwSDxteEHXczEZUXwvJdmcR46583R71CvD/c7sb5DWIlOt9jxm67FNOmoUBrEa6ssYIeCakV5OppM5ZDxgyZ4QyRMD8vTfoJEmVtflSaivjw9rUoINLynxekKEI4A=
        app:
          ortosia-postproc: decide-ortosia-postproc
      if: branch = ortosia-postproc AND type = push
